### ISSUE TITLE
wings attitude on final

### ISSUE THREAD

**Issue by pmaartense** [TwinFan/LiveTraffic#116]
yesterday i saw all planes that where on final into Taipeh , having their wings dropped 30 degrees to the right.

not just once but almost every plane showed that behaviour

**Comment by TwinFan** [comment]
Lucky you, that I saw that, too...as with this little information I wouldn‘t have had a chance to analyze. (The Bug form would have asked you the right questions.)

Anyway, reason is a bit trick to explain...has to do with the fact that the plan starts to roll _before_ reaching a turning point and usually rolls back to level wings _after_ passing that turning point and heading to the next know position. When LT runs out of tracking data for a plane (which can happen during approach due to bad coverage) then there is no next known position and LT forgot to roll the plane back to level. That was most often seen during an auto land when LT keeps the plane flying although there is no more data.
That has been fixed in v0.94.
Also, I made sure that latest during flare the plane rolls back to zero bank.
