### ISSUE TITLE
Priority for aircrafts in front

### ISSUE THREAD

**Issue by OE3GSU** [TwinFan/LiveTraffic#120]
**Current Situation / Problem**
Most of the time i see many aircrafts behind or beside me.

**Suggested Solution**
Is it possible, to display the aircrafts in front of my plane with priority?

**Alternatives**
dont know

**Benefits**
better display in the ND of XHSI (working perfect wirth LT, thanks!)

**Additional context**
none

**Comment by TwinFan** [comment]
Are you talking about TCAS blibs? (I suppose so only because you mentioned the ND, which might display TCAS blibs.)

If we assume you talk about TCAS blibs I understand the reasoning of the issue:
- There is a limited number of TCAS blibs.
- You prefer those TCAS blibs to represent the planes in front of you rather than behind you because those are most relevant to be avoided in-flight.

That makes sense and can be done. Currently, the ordering is strictly by distance, but adding a factor for bearing is not a big deal. (Implementation idea: reduce calculated distance of planes in front (0° bearing) to 25%, planes to the side (90° bearing) to 50%, Etc., while planes in the back are considered with their actual distance. That gives planes in front a 4x higher probability to be included. So prio-distance is:
```
(1 - 0,75 * (1 - abs(bearing) / 180)) * distance
```

Side note: With #117 it might be possible to increase the number of TCAS blibs to 19 no matter how many AI aircrafts are configured. The the priority becomes less of an issue...but is still a reasonable idea.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OE3GSU** [comment]
Hi!
I'm talkibng about TCAS blibs and the planes in the sim. When i'm flying with 490 kts GS i'm interested in the planes in front of me and coming from the side into my way. Your approach seems to be a good idea and i hpoe i can see it in version 1.0!
Best regards
Gerhard, Oe3gsu

**Comment by TwinFan** [comment]
Other idea: The position fed into data fetching functions currently just is the camera position. This serves as the center point for all traffic requests.

We could manipulate this position to "look ahead", i.e. have the center point be "in front" of us, the faster we fly the further ahead. Has the benefit of no tricks in libxplanemp and would also affect actual plane fetching and not only TCAS...hm...if we could feed this look ahead-position into libxplanemp...which we probably can't. But we could apply the same algorithm there...

**Comment by TwinFan** [comment]
Highest prio for planes in a 30° sector in front.
Second highest for 90° sector in front.
