### ISSUE TITLE
Cloud texture glitches with LT active

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#122]
**Describe the bug**
JRadest reports: „Got these﻿﻿﻿ weird texture glitches today while flying. As soon as I disabled the Livetraffic plugin, they disappeared. Tested it a few times and seemed to be when flying around clouds. ONLY happened when Livetraffic was running. Thought I'd send it to you, I'm using the latest update. “

**To Reproduce**
Activate LT in standard X-Plane 

clouds.

**Expected behavior**
No glitches, no influence on other graphic rendering.

**Screenshots**
![892A4FC6-5FD0-417F-85A5-DD6B156C11B5](https://user-images.githubusercontent.com/44291093/54305104-eb000900-45c6-11e9-8543-8bd04ab253ec.jpeg)
![0560A9B9-B33A-4843-8FA6-551FF1492E61](https://user-images.githubusercontent.com/44291093/54305105-eb000900-45c6-11e9-8f7f-0fdb3c17ca09.jpeg)

**Technical Info:**
 - OS: Windows 10
 - X-Plane version: 11.32r2 (build 113201 64-bit)
 - LiveTraffic version: v1.00

**Log.txt**
The following log is from that installation but not from the run with cloud glitches:
[Log.txt](https://github.com/TwinFan/LiveTraffic/files/2968141/Log.txt)

**Comment by TwinFan** [comment]
Flag also had that issue on Linux. Here also take not of the affected turbine heat blur of the default MD-88 in front:
![image](https://user-images.githubusercontent.com/44291093/55675440-e1ff1080-58c2-11e9-8f1d-53cb2b38e328.png)

**Comment by TwinFan** [comment]
Discord user Brandon V. reported something similar stating:

> 1. X-Plane Verison 11.32r2
 Live Traffic v1.10_190406
> 2. Get rid of these weird lines displayed in the sky
> 3. I could not find anything within the entire guide talking about visual/graphic error like this
> 4. It is creating theses werid lines in the sky ONLY when I switch TCAS control over from xSquawkBox (by disabling it in Plugin Admin) to LiveTraffic
> 5. Attached
> 6. Could it possibly be reshade causing this issue?

**Comment by TwinFan** [comment]
User slgoldberg reports:

> I guess you already know this, but just in case: the weird cloud texture artifacts appears even before you have any aircraft to render! In other words, after some time of running and seeing the texture artifacts periodically, I toggled display off (i.e., using menu "aircrafts displayed". )... when I then re-display aircraft using the same menu item, *immediately* the texture artifacts appear, well before it's begun actually trying to look for aircraft to render.

**Comment by slgoldberg** [comment]
I've been working to solve this, somehow, on my own for a while now. And I think I've landed on the solution -- at least, I think I'm on the right track.

The interesting data-point that helped me find this is that the "artifacts" would appear immediately coincidentally with the LiveTraffic message window being displayed.  In other words:  I noticed that the rare few times I was able to actually witness the first texture glitch appear, it was *always* at the same time as LiveTraffic's message window (in the upper right) would display a message.

For example, in my comment above, it was because literally at that instant, LiveTraffic had opened its message window and reported that it was starting up.  Armed with that knowledge, I started looking at why that may be the case, and I think it's actually an X-Plane bug (probably due to some minor issue in their Vulkan refactoring/rewrite that has affected XPLMDrawTranslucentRectangle() for the geeks among you).

So I've submitted a pull request to work around this by drawing the message window differently, and by only creating & destroying the window and all its widgets once per session, instead of every time a message is displayed. I think the combination has solved this -- i.e., I have not seen the problem since running LiveTraffic with my change. Thanks.

For users who don't want to wait for this to make its way into the plugin -- simply try changing your LiveTraffic settings to display messages only for Errors, and I think you'll see an improvement. (However, you'll still see the glitches, just not as frequently, until the full solution is adopted, because the settings widget itself can also trigger them.)

To be clear, this is a workaround -- the glitches could still appear, but after my proposed changes, I think the probability is that they would appear the very first time the settings window is opened. But if you get past that moment, there is zero chance it would happen after that (with my workaround).

Thanks.

 Steve

**Comment by TwinFan** [comment]
While I will not likely not pull the complete request #150 for its complexity and other changes I have reconciled two elements suggested by @slgoldberg, which might fix this bug:

- Text info window is not recreated, but only hidden (unfortunately, this does not as hoped avoid drawing the input focus away from somewhere else...to reduce the effect I have increased `WIN_TIME_REMAIN` to 1s so the window has less chances to be removed while subsequent msgs come up)
- The OpenGL code to replace `XPLMDrawTranslucentDarkBox` which @slgoldberg says to avoid this cloud texture glitches issue.

**Comment by TwinFan** [comment]
With reimplemented XPMP2 this is unlikely to appear again. Close in 2 months time if no new reports come in, ie. July.

**Comment by TwinFan** [comment]
Have not heard from this issue in v2 after switch to XPMP2. Closed.
