### ISSUE TITLE
Slave mode: Show a/c another LiveTraffic computes

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#126]
**Current Situation / Problem**
In complex X-Plane setups with multiple instances running interconnected LiveTraffic would produce independently computed planes. They wouldn't hand over nicely between screens computed by the individual instances.
Also, libxplanemp's culling is very strict, cutting off planes when leaving a window with its center already...that is clearly visible even in a one monitor setup.

See [this question](https://forums.x-plane.org/index.php?/files/file/49749-livetraffic/&do=findComment&comment=267195) on X-Plane.org.

**Suggested Solution**
Some kind of Master/Slave mode, in which slave instances receive data from a master instance.
Which data exactly? Well...two places are thinkable where to inject data: Into `mapFd`, i.e. full `LTFlighData` objects, or only at the interface into `LTAircraft`, i.e. basically when `LTAircraft` asks for new data .5s before a position is reached. (Upon entry I prefer the interface into `LTAircraft` as that is smaller. Only need to solve how to initially _create_ an `LTAircraft` in the slace instance then and where to attach...it needs some `LTFlightData` object to work with.)

One could think that just feeding LT's data (similar to the Foreflight sender #47) would be sufficient...but there is an awful lot of post-processing to received flight data so that a slave instance would come up with some other path in detail and planes wouldn't match up exactly at screen boundaries. But, hey...in slave mode or for that specific LT-internal channel all this smoothing could be switched off...and then the slave would work on exactly the same positions as the master which would -- given _exactly_ the same time on all computers -- result in the same plane movements with only very little network traffic.

**Benefits**
Smooth transition of planes in a multi instance setup.

**Additional context**
This is probably not too often a setup and I would have tremendous difficulties testing it. But it is definitely a cool problem ;)

**Comment by HellGL** [comment]
Hi,
I would love to see this feature somehow implemented! Wouldn't it be cool to sit on top of the Frankfurt Tower and see all the planes going in and out (e.g. [here](https://www.at-one.aero/pano/ats360/))?

We run several flight simulators based on X-Plane for the simulation itself as well as for the visualization. X-Plane slave instances are called "External Visuals" and receive not only position and orientation data from the master instance but also (probably among others) daytime and weather settings so that the lighting and shadows are the same on all slaves and the clouds span nicely over the whole sky (see [here](https://forums.x-plane.org/index.php?/forums/topic/21533-screenshot-themes-thread/&do=findComment&comment=1393613)). Probably multiplayer information are transmitted too. As the "External Visuals" interface also does some position interpolation on the slave instances it doesn't work in our dome projections very well where the images of 3 or 4 projectors are blended to a big screen: on faster roll or pitch maneuvers straight lines tear apart in the blending zone (even on very high fps on all instances). Therefore I implemented a plugin that reads in a list of DataRefs and sends them together with the aircraft position via the X-Plane native UDP interface to a list of X-Plane instances on the network. In this way I am able to control my 3 or 4 slaves very smoothly even on lower fps.

Wouldn't it be possible to export the positions of the instanced aircraft as DataRefs to be sent to the slave X-Plane instances where a minimal plugin only creates the aircraft and displays them on the received position? It is not necessary to create DataRefs, the bare minimum data to display the aircraft at the correct position, orientation and configuration maybe as multicast to a local network should be sufficient to drive a small plugin on the slave to display them. 

If there is anything I could do I would be happy to assist.

**Comment by TwinFan** [comment]
Coincidentally, in the past days I was thinking about using a UDP-based approach, too, seeing how X-Planes transmits data even in high frequency via its port 49000.
On the receiving side you'll need a bit more than a little plugin...you'll actually need 80% of LiveTraffic:

- _Positional_ information need to be received in high frequency, but as there is still no guarantee that there is fresh data for each and every drawing cycle there still needs to be minimum interpolation
- Live model _configuration_ needs to be transferred, too, for each of the [animation dataRefs](https://twinfan.github.io/XPMP2/CSLdataRefs.html) that drive the models (gear, flaps, wheels...)
- I am not sure that all that data can be transmitted successfully at 60Hz for 100 planes, that might just be a bit too much even for local networks. So the data needs to be reduced, which means again: more interpolation on the remote end
- The CSL model needs to be found and loaded locally...original matching might be done by the master, but the remote instance still needs to find the model/livery on disk and load it...and it needs to do something (well: its own matching) if that exact model isn't locally available
- You need the ability to configure also the remote instance, so the principal UI capability is in, too...then we can also drive all windows

I am pondering if I can move essential parts even into the [XPMP2 library](https://github.com/TwinFan/XPMP2), so that other plugins can benefit from it, too.

I'm not done yet with the design. As said...it's a not an easy thing to do, but I start loving that challenge.

**Comment by HellGL** [comment]
In our ATC simulation the position updates are created every 1000ms for fixed aircraft on the ramp and every 250ms for moving aircraft. The date is distributed in the local network via RabbitMQ. A central controller software gets the position updates for all variable objects in the simulation and by means of interpolation position updates are generated every 8ms (125Hz) which is twice the frequency the IGs are running at. The IGs are connected via [CIGI](https://en.wikipedia.org/wiki/Common_Image_Generator_Interface) to the controller software, which sends the data via UDP multicast. 

Maybe it could be a way to implement "LTAircraft via UDP multicast" as additional flight data channel and bypass for this channel all position interpolation. If I read the code correctly the positions are interpolated to every flightloop cycle. This would lead to jitter if the receiver is not synced to the same frequency and phase, especially visible if the camera is attached to one of the external aircraft. So on the sender side it is necessary to interpolate with a much higher frequency to make sure there is always a reasonably recent position for drawing available. But all interpolation must be done inside the sender and not the receiver as otherwise positions will certainly not fit from on channel to the next. In terms of network bandwidth I think event transferring 100 aircraft at a time should be no problem. At least there are protocols and techniques available that have proven to be suitable for this task (e.g. CIGI). 

For now I will install LiveTraffic in our helicopter sim (4 projectors in a 2x2 setup) and see how it looks. I think I will need to get some traffic recording and play it back to test under stable conditions.

**Comment by HellGL** [comment]
I have thought about it a little bit more and also had a deeper look into the code. Here are my comments to your original reply:

> Coincidentally, in the past days I was thinking about using a UDP-based approach, too, seeing how X-Planes transmits data even in high frequency via its port 49000.

While this is a way to communicate directly with X-Plane on the base of DataRefs with no overhead on the X-Plane side there is probably a better way to send and receive data if you already have a plugin running. As the DataRef names are transmitted as fixed char arrays the UDP packages carry unnecessary overhead. There are some particular packages however for e.g. postition updates (VEHX for driving external visuals) that are small and efficient. 

> DataRefs are in principle [already available](https://twinfan.gitbook.io/livetraffic/introduction/features/api), but not in a pure array form that could easily be used right away. There even is an API that can process LiveTraffic's data in full from another plugin. The data is internally certainly transferred by dataRef - as a binary blob.

I had a look at the LTAPI and the example code. This could be used to access the data and send it directly via multicast. 

> I am pondering if I can move essential parts even into the [XPMP2 library](https://github.com/TwinFan/XPMP2), so that other plugins can benefit from it, too.

With the new instancing feature of X-Plane 11 XPMP2 could be not only a multiplayer library but an universal library to move and animate other objects (people, cars etc) in X-Plane as well.

> 
> On the receiving side you'll need a bit more than a little plugin...you'll actually need 80% of LiveTraffic:
> 
>     * _Positional_ information need to be received in high frequency, but as there is still no guarantee that there is fresh data for each and every drawing cycle there still needs to be minimum interpolation

Lets give it a try. If the sender is not at 20Hz you might not even see it.

> 
>     * Live model _configuration_ needs to be transferred, too, for each of the [animation dataRefs](https://twinfan.github.io/XPMP2/CSLdataRefs.html) that drive the models (gear, flaps, wheels...)

Sure. 

>     * I am not sure that all that data can be transmitted successfully at 60Hz for 100 planes, that might just be a bit too much even for local networks. So the data needs to be reduced, which means again: more interpolation on the remote end

That is no Problem. We transmit Full HD textures to be displayed on stereo HMDs at 60Hz via multicast. 

>     * The CSL model needs to be found and loaded locally...original matching might be done by the master, but the remote instance still needs to find the model/livery on disk and load it...and it needs to do something (well: its own matching) if that exact model isn't locally available

In a setup like this it should be no problem to have a networked installation or sync the data over all instances via cloud storage. So model matching and so on is only needed on the sender side and maybe fallback to a big red X to indicate that there is something missing. 

>     * You need the ability to configure also the remote instance, so the principal UI capability is in, too...then we can also drive all windows

There should be no configuration necessary for a setup like this. Otherwise it could be done via UDP DataRef transmission. 

> I'm not done yet with the design. As said...it's a not an easy thing to do, but I start loving that challenge.

Me too:-)

**Comment by TwinFan** [comment]
I will solve that in XPMP2 and have opened TwinFan/XPMP2#22 for that.
