### ISSUE TITLE
Crash to Desktop After Addition of RealTraffic

### ISSUE THREAD

**Issue by acl9787** [TwinFan/LiveTraffic#133]
After the addition of RealTraffic data, Livetraffic appears to cause x-plane to crash at random points during the flight.  X Plane (and sound) stutters several times before the crash.  This issue did not occur prior to utilizing RealTraffic.

Log.txt files from two separate instances are attached.
[Log 4-28-19.txt](https://github.com/TwinFan/LiveTraffic/files/3125621/Log.4-28-19.txt)
[Log 4-21-19.txt](https://github.com/TwinFan/LiveTraffic/files/3125622/Log.4-21-19.txt)

**Comment by TwinFan** [comment]
Please add the crash dumps, see [here](https://twinfan.gitbook.io/livetraffic/reference/help-and-support#x-plane-quit-unexpectedly) how to get them.
And I would appreciate if you‘d use provide templates when entering issues as they ask relevant questions.

The end of the log is a bit a surprise...never seen that before. But the included backtrace ends in LiveTraffic, so I have hope that the dump help.

**Comment by acl9787** [comment]
Sorry - it appears that X-plane did not publish a crash report for either of these instances.  The latest file I have in that folder is from September 2018.  Below is the full template information:

**Describe the bug**
After the addition of RealTraffic data, Livetraffic appears to cause x-plane to crash at random points during the flight. X Plane (and sound) stutters several times before the crash. This issue did not occur prior to utilizing RealTraffic.

**To Reproduce**
1. Start flight with Livetraffic and Realtraffic enabled
2. Realtraffic running with Standalone file
3. Typically 1/2 to 3/4 of way into flight, X-plane stutters (sound cuts out unlike normal stutters) and crashes to desktop
4. I have tried this with and without AI planes enabled, and both result in CTD
5. I ran an additional flight last night with LiveTraffic plugin removed without CTD

Reproducing issues with the modelling/display of live aircrafts is next to impossible. Remember, that LiveTraffic relies on live flight data from various public sources. They aren't accurate to the feet. If, however, you observe a behaviour more or less repeatedly when 'watching' live data then provide:
1. Location (preferably airport, coordinates otherwise) - Does not seem to impact the bug
2. Weekday / Time of day (scheduled flights tend to repeat at least weekly) - Does not seem to impact the bug
3. additional pattern like aircraft type, heading, altitude, flight phase... - typically happens in cruise or before approach
4. A Log.txt file with log level (Settings/Advanced) set to 'Debug'

**Expected behavior**
Expect not to CTD when under normal conditions

**Screenshots**
None available

**Technical Info:**
 - OS: [Mac/Win/Linux] - Windows 10
 - X-Plane version: 11.32
 - LiveTraffic version: Livetraffic v.1.10_190406
-  Realtraffic Standalone version - 6.036

**Log.txt**
Attach your Log.txt file, if reproducible then please reproduce with log level (Settings/Advanced) set to 'Debug' first.

**Comment by TwinFan** [comment]
Thx for the additional info.

What I read from the logs:

**Sun Apr 21 16:43:04 2019**
Contains next to no info from LiveTraffic. It loaded OK, but then not even an info that it was activated and tried to display aircrafts. That could be due to a very reduced setting...or it just wasn't activated. The only message was
```
LiveTraffic 1555879448.1 ERROR src\LTVersion.cpp:221/FetchXPlaneOrgVersion: Could not browse X-Plane.org for version info: 35 - schannel: failed to receive handshake, SSL/TLS connection failed
```
which I think unusual, but points to issue in network setup, hard to believe it would be related to a crash minutes later.
The entire log doesn't really contain much...there is a huge gap between line 537 (logged at runtime 0:03:17) and line 539 (logged 43 minutes later at 0:46:22). Unlikely that nothing happened during that time.

The actual crash ends with:
```
019-04-21 18:29:00 TBM900[except.c:171]: Caught EXCEPTION_ACCESS_VIOLATION
Backtrace is:
0 000001ECE6A303C4 C:\Users\Andy\Desktop\X-Plane 11\X-Plane.exe+000001ECE6A303C4 ()
1 0000000000000001 C:\Users\Andy\Desktop\X-Plane 11\X-Plane.exe+0000000000000001 ()
```
referring to TBM900. This seems to be a rather complex airplane: `Aircraft/X-Aviation/TBM-900/TBM900.acf`. This alone has 108 mentions in the Log.txt and loads at least 3 further plugins:
```
2019-04-21 16:43:52 OpenGPWS[xplane.c:190]: This is OpenGPWS (ca8e3e1) libacfutils-53c1d93
Loaded: C:\Users/Andy/Desktop/X-Plane 11/Aircraft/X-Aviation/TBM-900/plugins/OpenGPWS/win_x64/OpenGPWS.xpl (skiselkov.opengpws).

2019-04-21 16:43:52 OpenWXR[xplane.c:121]: This is OpenWXR (1fbc878) libacfutils-53c1d93
Loaded: C:\Users/Andy/Desktop/X-Plane 11/Aircraft/X-Aviation/TBM-900/plugins/OpenWXR/win_x64/OpenWXR.xpl (skiselkov.openwxr).

2019-04-21 16:43:52 xtcas[xplane.c:670]: This is X-TCAS version 7e3db7 (confopts: VSI:0 STYLE:1 GTS820:1)
Loaded: C:\Users/Andy/Desktop/X-Plane 11/Aircraft/X-Aviation/TBM-900/plugins/X-TCAS/win_x64/X-TCAS.xpl (skiselkov.xtcas).
```
The first line of the crash notice, `2019-04-21 18:29:00 TBM900[except.c:171]: Caught EXCEPTION_ACCESS_VIOLATION`, means that the plugin redirection exception handling to itself.
Why would they do that??? This might well be the reason why there is no dump. X-Plane wasn't even informed and had no chance of doing his own crash reporting.

The 2 lines of backtrace point into the guts of X-Plane.exe.

Summary: There is no trace to LiveTraffic in this log. There is no hint that LiveTraffic is involved in it crashing.

**Sun Apr 28 15:30:36 2019**

Also very short with apparent gaps. There is a bit more on LiveTraffic, 3 occurences of warnings regarding missing ICAO a/c code in the tracking data. So here it is at least clear that LiveTraffic did run and showed aircrafts.

Again, exception handling was caught by TBM900. The backtrace in this case is a lot longer:
```
2019-04-28 16:22:58 TBM900[except.c:171]: Caught EXCEPTION_ACCESS_VIOLATION
Backtrace is:
0 00007FFA15C961D9 C:\Users\Andy\Desktop\X-Plane 11\Resources\plugins\LiveTraffic\64\win.xpl+00000000000561D9 ()
1 00007FFA15C6EC44 C:\Users\Andy\Desktop\X-Plane 11\Resources\plugins\LiveTraffic\64\win.xpl+000000000002EC44 ()
2 00007FFA15D88FE4 C:\Users\Andy\Desktop\X-Plane 11\Resources\plugins\LiveTraffic\64\win.xpl+0000000000148FE4 ()
3 00007FFA15C72C6F C:\Users\Andy\Desktop\X-Plane 11\Resources\plugins\LiveTraffic\64\win.xpl+0000000000032C6F ()
4 00007FFA15C72C60 C:\Users\Andy\Desktop\X-Plane 11\Resources\plugins\LiveTraffic\64\win.xpl+0000000000032C60 ()
5 00007FFA15C72C60 C:\Users\Andy\Desktop\X-Plane 11\Resources\plugins\LiveTraffic\64\win.xpl+0000000000032C60 ()
6 00007FFA15C72C60 C:\Users\Andy\Desktop\X-Plane 11\Resources\plugins\LiveTraffic\64\win.xpl+0000000000032C60 ()
7 00007FFA15C7257F C:\Users\Andy\Desktop\X-Plane 11\Resources\plugins\LiveTraffic\64\win.xpl+000000000003257F ()
8 00007FFA15C72DEF C:\Users\Andy\Desktop\X-Plane 11\Resources\plugins\LiveTraffic\64\win.xpl+0000000000032DEF ()
9 00007FFA15DAF168 C:\Users\Andy\Desktop\X-Plane 11\Resources\plugins\LiveTraffic\64\win.xpl+000000000016F168 ()
10 00007FFA76C2FCB3 C:\WINDOWS\System32\ucrtbase.dll+000000000000FCB3 ()
11 00007FFA76C2F967 C:\WINDOWS\System32\ucrtbase.dll+000000000000F967 ()
12 00007FFA76C2F924 C:\WINDOWS\System32\ucrtbase.dll+000000000000F924 ()
13 00007FFA15D62AE2 C:\Users\Andy\Desktop\X-Plane 11\Resources\plugins\LiveTraffic\64\win.xpl+0000000000122AE2 ()
14 00007FFA15D62C08 C:\Users\Andy\Desktop\X-Plane 11\Resources\plugins\LiveTraffic\64\win.xpl+0000000000122C08 ()
15 00007FFA798CB583 C:\WINDOWS\SYSTEM32\ntdll.dll+000000000003B583 ()
16 00007FFA798D7F85 C:\WINDOWS\SYSTEM32\ntdll.dll+0000000000047F85 ()
17 00007FFA798D7E48 C:\WINDOWS\SYSTEM32\ntdll.dll+0000000000047E48 ()
18 00007FFA7725CA7A C:\WINDOWS\System32\KERNEL32.DLL+000000000001CA7A ()
19 00007FFA76ED9CE5 C:\WINDOWS\System32\msvcrt.dll+0000000000039CE5 ()
20 00007FFA76EDA345 C:\WINDOWS\System32\msvcrt.dll+000000000003A345 ()
21 00007FFA76ECEE5D C:\WINDOWS\System32\msvcrt.dll+000000000002EE5D ()
22 00000000809CF802 C:\Users\Andy\Desktop\X-Plane 11\Aircraft\X-Aviation\TBM-900\plugins\systems\win_x64\systems.xpl+00000000009DF802 ()
23 00000000809CF8B7 C:\Users\Andy\Desktop\X-Plane 11\Aircraft\X-Aviation\TBM-900\plugins\systems\win_x64\systems.xpl+00000000009DF8B7 ()
24 0000000080189B29 C:\Users\Andy\Desktop\X-Plane 11\Aircraft\X-Aviation\TBM-900\plugins\systems\win_x64\systems.xpl+0000000000199B29 (cairo_scaled_font_destroy+c9)
25 00000000801A5C11 C:\Users\Andy\Desktop\X-Plane 11\Aircraft\X-Aviation\TBM-900\plugins\systems\win_x64\systems.xpl+00000000001B5C11 (_cairo_gstate_rotate+51)
26 0000000080195409 C:\Users\Andy\Desktop\X-Plane 11\Aircraft\X-Aviation\TBM-900\plugins\systems\win_x64\systems.xpl+00000000001A5409 (cairo_rotate+19)
27 000000008002CEA5 C:\Users\Andy\Desktop\X-Plane 11\Aircraft\X-Aviation\TBM-900\plugins\systems\win_x64\systems.xpl+000000000003CEA5 (draw_perf_ind+805)
28 000000008002EB3A C:\Users\Andy\Desktop\X-Plane 11\Aircraft\X-Aviation\TBM-900\plugins\systems\win_x64\systems.xpl+000000000003EB3A (eicas_render+11a)
29 000000008014E136 C:\Users\Andy\Desktop\X-Plane 11\Aircraft\X-Aviation\TBM-900\plugins\systems\win_x64\systems.xpl+000000000015E136 (worker+136)
30 00007FFA77254034 C:\WINDOWS\System32\KERNEL32.DLL+0000000000014034 ()
31 00007FFA79903691 C:\WINDOWS\SYSTEM32\ntdll.dll+0000000000073691 ()
```
But funny thing is: The backtrace starts in the TBM900 plugin. That was apparently busy rendering an EICAS...then somehow, through a couple of system calls, got into LiveTraffic while destroying a scaled font??? Seems like the operating systems called LiveTraffic. There is no intermediate call into xplane.exe (like it would be in case of dataRef reads). So somehow both LiveTraffic and TBM-900 are holding reference to a common resource???

This is completely mysterious. Obviously LiveTraffic played some weird role in the crash. I seriously doubt it has anything at all to do with RealTraffic as a channel. I don't see traces of RealTraffic...probably due to reduced logging settings. Doesn't make the analysis job easier...

Once I am on Windows I might want to try resolving the addresses in the backtrace if at all possible. A dump would be so much easier.

In the meantime you may want to try two things to rule out possibilities:
1. Run LiveTraffic, but not with RealTraffic as a feeding channel. Rely on OpenSky. And use the TBM-900 airplane. Chances are that it crashes.
2. Load LiveTraffic (don't remove from plugins it like you tried already), but don't activate it, i.e. make sure that "Aircrafts displayed" is off. Use the TBM-900. I think a fifty-fifty chance of crashing.
3. Run LiveTraffic with RealTraffic, the full monty, but use another plane. My guess: Will not crash.
(And of all crashes I certainly like to see the full Log.txt)

If all that is true then we would need the place where TBM-900 and LiveTraffic get into conflict.

I seriously think that the TBM-900 plays a major role, too. That is the only thing that appears consistently in both logs during the crashes. Well...and googling for it brings up a [lengthy forum post on crashes of TBM-900](http://forums.x-pilot.com/forums/topic/15608-caught-exception_access_violation/). And a very [fresh one, just Friday](http://forums.x-pilot.com/forums/topic/16331-tbm900exceptc171-caught-exception_access_violation/). And many more. Please google for "TBM900[except.c:171]: Caught EXCEPTION_ACCESS_VIOLATION site:forums.x-pilot.com"

**Comment by acl9787** [comment]
I'm sorry that I haven't had time to run all the scenarios you mentioned above, but I have experienced further crashes with the TBM-900 with the LiveTraffic plugin deactivated (see attached additional log file).  This leads me to believe the TBM is at fault rather than LiveTraffic.  The TBM developers stated they're looking into this.

I have re-enabled LiveTraffic with another plane (scenario 3) and have not experienced any crashes.

Just wanted to close the loop on this a bit - thanks for your responses.
[Log 5-7-19.txt](https://github.com/TwinFan/LiveTraffic/files/3163058/Log.5-7-19.txt)

**Comment by TwinFan** [comment]
Thanks for getting back in this matter! Wish, all people would do that. I'll close the issue for the time being. Can always be reopened if something points back to LiveTraffic.
