### ISSUE TITLE
X-plane crashes when LiveTraffic installed and FF A320's TCAS button is switched

### ISSUE THREAD

**Issue by xmska** [TwinFan/LiveTraffic#218]
**Describe the bug**
X-plane crashes when LiveTraffic installed and TCAS button is switched. It does not crash without LiveTraffic.

**To Reproduce**
1. Start Airbus A320 Ultimate with engines running
2. Click on TCAS to ALL

1. Location KJFK any rwy
2. anytime
3. on runway
4. A Log.txt file with log level (Settings/Advanced) set to 'Debug'
5. new clean install with no changed livetraffic config

[https://store.x-plane.org/A320-Ultimate_p_688.html]
[Log.txt](https://github.com/TwinFan/LiveTraffic/files/6873175/Log.txt)
[Log.txt](https://github.com/TwinFan/LiveTraffic/files/6873171/Log.txt)
![tcas](https://user-images.githubusercontent.com/34665097/126882974-e6c818ff-a787-40fd-a6e2-3d0ff57370cf.png)

**Screenshots**
Screenshot and two log.txt attached.

**Technical Info:**
 - OS: Win10
 - X-Plane version: 11.55r2
 - LiveTraffic version: 2.51

**Log.txt**

**Comment by TwinFan** [comment]
Chances are that it is one of the FF A320 plugins that crashes. In both cases the last log entries are by FF A320, though the last entries in the log is certainly no proof by itself. It only confirms that the FF A320 did something due to activating the TCAS display...and later on a crash occurred.

What is the difference with LiveTraffic running? _Without_ LiveTraffic (and no other similar plugin) only X-Plane's AI aircraft are shown as TCAS targets in an TCAS display. This will be as many as you configured AI planes, no more than 19. _With_ LiveTraffic, the difference is the _number of_ active TCAS targets an internal TCAS implementation (like the one for FF A320) would need to handle. _With_ LiveTraffic this can be up to 63. There have been several cases in which TCAS implementations were not able to handle more than 19 TCAS targets because 19 used to be a previous limit, lifted with XP 11.50. (proven examples: [Little XPConnect](https://github.com/albar965/littlenavmap/issues/520), [XHSI](https://forums.x-plane.org/index.php?/forums/topic/190603-roadmap-for-xhsi-20-beta-12/&do=findComment&comment=2170899), suspected examples: AviTab, most of them fixed now).

I have not yet heard of FF A320 being a problem, but we can figure this out now. Please do the following:

- As you are on Winodws you will [find a crash dump](https://twinfan.gitbook.io/livetraffic/reference/help-and-support#windows), please upload one of a recent crash of this type. With a little luck I can figure out in which module the crash happened or at least confirm that it was or was not LiveTraffic.
- Limit the number of planes in LiveTraffic to 19 as a test (set _Max. number of Aircraft_ to 19 in [Settings > Advanced > Aircraft Selection](https://twinfan.gitbook.io/livetraffic/setup/configuration/settings-advanced#aircraft-selection)), then only activate TCAS in the FF A320. My guess is: No crash because the FF A320 is capable of handling that many TCAS targets.
- When that runs fine, increase the number of aircraft back to 100 or whatever it was before. As soon as so many aircraft are actually displayed by LiveTraffic (watch number of _Live Aircraft Shown_ in the [Status window](https://twinfan.gitbook.io/livetraffic/using-lt/info-list-window/status-about)) the crash might happen again, which would be final proof that it is related to the _number_ of planes to display.

**Comment by xmska** [comment]
First off, the scroll bar won't let me to set Max. number of Aircraft to 19. If I scroll to 19 with the left mouse button and then release the button, it changes to some other near number like 15, 20. I suggest it would be nice to fix the scrollbar.

I set 15 and it worked. And it crashed again with 20.
I attached new log.txt and prt crash dump.

So, is this a bug in the plane A230 and I should report to FlightFactor?

[crash_report_07_25_2021_21_06_56.zip](https://github.com/TwinFan/LiveTraffic/files/6874573/crash_report_07_25_2021_21_06_56.zip)
[Log.zip](https://github.com/TwinFan/LiveTraffic/files/6874574/Log.zip)

**Comment by TwinFan** [comment]
The _Max. number of Aircraft_ setting might indeed snap to multiples of 5...but you tested it the right way: All good with 15, crash with 20: this indicates a problem with the FF A320 implementation.

Tomorrow I can have a look into the provided crash report for confirmation.

**Comment by xmska** [comment]
Now it crashed again with LiveTraffic plugin disabled and with 19 AI Aircrafts. I sent the log to FlightFactor, see if they can fix it.

**Comment by TwinFan** [comment]
...and I have looked into the crash dump: Crash location was in file
`C:\X-Plane 11\Aircraft\Laminar Research\FlightFactor A320 ultimate\plugins\systems\64\win.xpl`.

So, yes, please report this to FightFactor. Provide them with the crash dump, that I extracted from the `.rpt` file:
[crash_report_07_25_2021_21_06_56.dmp.zip](https://github.com/TwinFan/LiveTraffic/files/6876841/crash_report_07_25_2021_21_06_56.dmp.zip)

You can point them to this issue thread and ask them:
- Watch for the fact that [`XPLMCountAircraft`](https://developer.x-plane.com/sdk/XPLMPlanes/#XPLMCountAircraft) can return numbers larger than 20 since XP11.50b8.
- Quick fix: Limit returned numbers to internal array length, typically 19 or 20.
- Long-term fix: Implement new approach as outlined in Laminar's [TCAS Override](https://developer.x-plane.com/article/overriding-tcas-and-providing-traffic-information/#New_datarefs) document.

**Comment by xmska** [comment]
I sent the info to FightFactor.

But what tool did you use to extract the dmp file from the rpt?

**Comment by TwinFan** [comment]
Notepad++ and certutil.

The `.rpt` file is just a text file with a JSON-like structure. It's node "dmp_file" is the dump file in Base64 encoding. So I remove all other text around the Base64 encoding, save it as a new `.b64` file and have it decode with a call to `certutil -decode foo.b64 foo.dmp`.

**Comment by xmska** [comment]
They told me to update to newer beta version which fixes the crash and it works. But it's strange to recommend users to do so as there is a warning about possible bugs in beta.

Thank you for your help.
