### ISSUE TITLE
Keep parked airplanes after they have turned off transponder

### ISSUE THREAD

**Issue by jorisrobijn** [TwinFan/LiveTraffic#255]
## Current Situation / Problem
Airplanes disappear when parked at a gate. This is because they turn off their transponder and therefore disappear from the list of received aircraft.

## Suggested Solution
When an aircraft has been received at an almost fixed position for some time and then disappears from the list, we can assume it is still there. Especially if this is at/near the position of an X-Plane ramp spot. The plane could then be kept there. 
Medium and large planes normally stay parked where they were stopped. But small airplanes are often moved inside. Therefore small airplanes should only stay for a few minutes, while medium and large airplanes can stay for a few hours.
In case the reception at an airfield is bad, or if no ADS-B but only multilateration is available, the aircraft may show its last position on the runway or in the air. Since this is far away from a ramp spot, it is better to make it disappear (probably we never observed the aircraft twice at the same position anyway). 

## More
Preferably, after restarting an X-Plane flight, the aircraft of a short time ago should be remembered. Otherwise at every restart at the same airport, all planes that have just landed are forgotten. However, after a few hours this information cannot be used anymore.

If ramp spots are identified for the parking location, this information is also available for pushing back the airplane from the gate when it leaves. This is described in issue #217 .

In the future, maybe the aircraft parked at gates could use ground service from X-Plane.

## Benefits
This fills the airports a bit with parked aircraft. And they don't just disappear.

**Comment by TwinFan** [comment]
Yea, that has been suggested a couple of times, but apparently not entered as an issue here yet, so thanks for adding.

It isn't even terribly difficult to implement, at the least the part to just keep already existing planes (not cars) a little longer. LiveTraffic is aware of the airport's parking positions, so it can judge if the aircraft is near such a spot when the signal is lost and can just keep the plane as it is.

LiveTraffic can also determine when -for whatever weird reason- _another_ plane (not car) shows up way too close and would then eventually remove the parked plane.

I would _not_ invest in "remembering" any position between starts of the X-Plane simulator (which you probably didn't intend to suggest anyway).

I _might_ look into keeping parked planes across automatic resets that you may potentially experience when setting up a new flight. These resets happen because LiveTraffic isn't called by X-Plane while you are in a main menu and hence can't get position updates. This reset is currently quite radical, so can't say off hand if keeping any planes is reasonably possible without rewriting too much code.

**Comment by jorisrobijn** [comment]
Sounds good. I understand the difficulties. If you can retain the list of aircraft between restarts/continuations (not full restarts of X-plane) that would be very nice. Maybe you can find an other way to decide if you can still use the data in the list for the movement calculations, or you need to "restart receiving".
