### ISSUE TITLE
Plane overtaking others on approach

### ISSUE THREAD

**Issue by CloudSkimmer** [TwinFan/LiveTraffic#43]
**Describe the bug**
A clear and concise description of what the bug is: What's wrong?
After taking off from LEBL and circling around to my heading, as I passed over the airport I could see planes lined up for landing. They looked spaced correctly, however, one plane came from behind and overtook the others at a high rate of speed. I was doing 250-270kn, not much faster than the plane in question.
**To Reproduce**
Take off from 07r at LEBL at approx 1500hr...weather was clear but windy..circle around at 3500ftagl over airport heading 250

I attached my log (debug was set) and a photo, while it was possible to read in flight, unfortunately, the photo is hard to distinguish the details. (Next time I will write it down!)
![b738_5](https://user-images.githubusercontent.com/45555040/49374731-80efe200-f702-11e8-9841-22cb4399b0e0.png)

**Technical Info:**
 - OS: Windows 10 64 pro
 - X-Plane version: 11.26
 - LiveTraffic version: 0.81.20181202
[Log.txt](https://github.com/TwinFan/LiveTraffic/files/2639472/Log.txt)

**Comment by TwinFan** [comment]
That's gonna be difficult to analyse without precise data. I see form the Log you ran OpenSky and ADS-B in parallel, that is allowed, but also good for issues.

Imagine (and I did see that also), that OpenSky and ADS-B data are slightly off by a few seconds. The plane would approach at, say, 160kn if reading channel A only. Then a data point from the other channel B comes in placing the plane closer to the runway but with a timestamp not too far away from the last one received from channel A (due to the fact that both channels aren't quite synched as we defined as the precondition). To make up for that LT would need to speed up that plane quite a bit and it overtakes all other planes which are controlled by channel A data only (because maybe they just don't appear on channel B).

Can't be proven from the log. Which, btw, ends on Monday, December 3, 2018 1:33:31.300 PM european time, it doesn't cover 15:00.
(The long number after the text "LiveTraffic" is just a Unix timestamp, which can be converted on web sites like [this one](https://www.epochconverter.com).)

Full analysis would only be possible with a network log.

To prepare for better analysis next time you may want to activate "Debug: log a/c positions" already. That places position information into the log for the plane selected in an a/c info window.

If you see something like that again (or any other suspicous plane) then try to identify the plane and open an a/c window for that plane. Then all future positions and decisions are logged into Log.txt. A full network.log would still be better as it would cover the history as well.

**Comment by TwinFan** [comment]
For better handling of multiple channels see #61.
