### ISSUE TITLE
Aircraft taxi in Rotate state / FD analysis re Rocket Planes

### ISSUE THREAD

**Issue by MuellerPatrick** [TwinFan/LiveTraffic#57]
**Describe the bug**
Some planes are taxiing with nose up in rotate state.

**To Reproduce**
Seen this on EGLL and LSZH

**Expected behavior**
Taxi with nose on the ground

**Screenshots**
Screenshots of 2 planes included.

**Technical Info:**
 - OS: Win10
 - X-Plane version: 11.30b7
 - LiveTraffic version: 0.83
[LTRawFD.log](https://github.com/TwinFan/LiveTraffic/files/2674837/LTRawFD.log)
![lt-rotatestate3c5eea](https://user-images.githubusercontent.com/45783857/49921555-3878b700-feae-11e8-9abf-72b3560624c5.png)
![lt-rotatestate](https://user-images.githubusercontent.com/45783857/49921558-3b73a780-feae-11e8-9818-c140e6477241.png)

**Log.txt**

**Comment by TwinFan** [comment]
Ups...but look how exactly they just don’t strike their tail...was a bit of tuning :)
Anyway need to have a look! The Log.txt doesn’t seem to have attached successfully, do you still have it? Would be helpful in this case.

**Comment by MuellerPatrick** [comment]
[Log.txt](https://github.com/TwinFan/LiveTraffic/files/2675017/Log.txt)
This is the log.txt..... done some things before and after the bug filed.
maybe the interesting part is somewhere in the middle.

**Comment by TwinFan** [comment]
First note: Both aircrafts were fed from both ADSBEx and OpenSky. 3C5EEA arrived in LSZH, 4B18F1 departed.

In the OpenSky stream of 4B18F1 there are null values for the altitude:
```
["4b18f1","SWR1726 ","Switzerland",1544683146,1544683147,8.5615,47.4601,null,true,0.13,95,null,null,null,"1000",false,0]
                                                                        ^^^^
```
They are likely interpreted as `0`. At the same time ADSBEx reports `"Alt":1375` [ft], later OpenDky resumes reasonable values, reporting `419.1` [m]. All this up and down might have caused the algorithm to think the plane would take off and calculated a rotate timestamp.

I see quite a lot of `null` values for altitude in the OpenSky data.

We just call `jag_n(pJAc, OPSKY_ELEVATION)`, which indeed returns `0` in all non-numeric cases.

We must capture this case of invalid data by explicitely checking for `null` and if so ignore that position - altitude is an essential part of a position and required for our purposes.

That should eliminate the `null` case. Still, combining two channels will probably trigger such a behaviour as above also just because the channels slightly differ in their altitude. If it is just 'slightly' nothing will happen as for a take off prediction we require a VSI > 100ft/m. But what if channels differ by that?

But that goes back to the issue of how to combine different channels' data. I've finally entered issue #61 for that.

**Comment by TwinFan** [comment]
OK, the idea is as follwos:
In CalcNextPos we introduce some more smoothing of positions in the following way:
- If the next message in the queue (after removing outdated ones based on timestamp)
    - forces the plane to a VSI of more than `+/- 2 * VSI_INIT_CLIMB` as per Flight Model, or
    - turns the plane by more than 120°
the next check applies: We do the same checks as above with the 2nd message waiting in queue. 
- If the 2nd message validates properly we simply drop the first in queue (which validated negatively) and work with the messages thereafter.
- Otherwise that means that 1st and 2nd message might make sense when viewed together, but they aren't connecting well with the current position. To avoid rocketing in that case we should just remove the aircraft `pAc` but keep the flight data. As we have valid positions in the queue standard Aircraft Maintenance will kick in soon and create an aircraft again, now probably elsewhere in the sky.

**Comment by TwinFan** [comment]
**Rocket Planes**: In each case I could analyse (and some of those I've experienced myself) I did find flight tracking data, which sent the plane up into the sky and back. So root cause is inaccurate flight tracking data, mostly by ADS-B-Exchange, but rarely also by OpenSky Network. For examples of data see [the comment above](https://github.com/TwinFan/LiveTraffic/issues/57#issuecomment-447311005).

Mixing channels can also cause the effect. ADSBEx and OpenSky are definitely out of sync. In EDDF it is about 30-45 seconds that ADSBEx positions trail behind. That means: With similar position timestamp the position of ADSBEx is where OpenSky was 30-45s earlier. During Approach, while continuously decreasing altitude, a sudden ADSBEx data point makes the plane move upward. That effect is not as strong as the 'real' rocket planes, but again ugly.

The latter is also, what causes 180° turns (to get to the ADSBEx position) twice (to get back to the next OpenSky position), totalling 360°.

And it causes confusion in take-off- and landing-prediction as a plane, which had already touched ground / lifted off can be forced to go back. That in turn can lead to planes moving around in **Rotate state**. (Such planes had touched down, then a data point back in position history makes them take off again and if ever so slighly, so they rotate, but that rotate phase is shortened as the plane chases the next data point back on the ground, so the plane never really lifts off, which so far was the only place to end the rotate phase. So they continue taxiing with their nose up...the rotate phase is a ground-bound phase in the end, thus, so far, the implementation was fine with that, but see below for a fix.)

I've done several enhancements to deal with the tracking data in order to soften the effects:
- **Mixing channels** is now officially supported: A plane will only be served by one channel (the one which happened to see the plane first). A switch to another channel is possible, but only if the original channel stopped sending data for roughly the `a/c outdated period` (Advanced Settings), and if the next position is in a reasonable direction to avoid 180° turns. As this still cannot and will never solve the fact that the channels are not time-synched there will still be effects during channel switch, specifically slow or fast moving planes to make up for the time difference. But at least direction of movement should be somewhat consistent. While now supported I will keep warnings in the documentation as to the combination of channels. A channel switch will be document with a DEBUG-level `Log.txt` entry like `DEBUG AA73C3 (SWA1730): SWITCHED CHANNEL from 'ADSB Exchange Live Online' to 'OpenSky Live Online'`
- An algorithm regularly loops over the positions in cache and performs some **data cleansing**, i.e. tries to identify invalid positions (by to high VSI, turn rate, speed) and removes them. Will be reported in `Log.txt` with a DEBUG-level entry like `DEBUG A25CDC (SKW4148): Removed an invalid position`. It's a bit more tricky than it sounds as it is quite hard to derive mathematical conditions for a task simple to humans ("looks weird, if removed track would look consistent") and still needs some ironing out. But it does already remove data points like above and hence removes rocket planes. Especially ADSBEx sends also some other weird stuff (planes moving sideways by long distances) which LT does not yet always identify correctly.
- Just in case...added timing to the **Rotate state**, so that a plane will no longer stay endlessly in that state with nose up.

**Comment by MuellerPatrick** [comment]
Thank you much for your explanation. Sounds good at all.

**Comment by CloudSkimmer** [comment]
Wow, thanks for the excellent detailed report. Gives us a sense of how this happens.  I did wonder about having different sources at once, but no idea it'd do the rocket or rotate swivel.  Just saw the PB v0.9..will apply on my next flight. Thank you again ;)
